# Generated by Django 5.2.3 on 2025-06-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritura', '0003_alter_escrito_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mostrar_en_comunidad',
            field=models.BooleanField(default=False, help_text='Marca esta casilla si deseas que tu perfil sea visible en la página principal.', verbose_name='Mostrar mi perfil en la página de la comunidad'),
        ),
    ]
