# Generated by Django 5.2.3 on 2025-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritura', '0005_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrito',
            name='notificacion_enviada',
            field=models.BooleanField(default=False, verbose_name='Notificación Enviada'),
        ),
    ]
